import openNextWorker from 'open-next-worker'

/**
 * The single deployed Worker.
 *
 * `fetch` delegates to the handler generated by `@opennextjs/cloudflare`.
 * `scheduled` is the one entry point for background work: it invokes Payload's
 * native job queue over the application's own request pipeline, so the job runs
 * with the same bindings, the same `process.env` population and the same
 * database connection policy as a normal request. There is no second worker and
 * no in-memory timer.
 *
 * `open-next-worker` is the build artifact `.open-next/worker.js`, mapped by the
 * `alias` entry in `wrangler.jsonc`. Types come from the adapter's own template
 * declaration through `tsconfig.json` `paths`, so `pnpm typecheck` does not
 * require a prior build.
 */

/** Upper bound on jobs drained per cron tick. Bounded by design. */
const JOB_BATCH_LIMIT = 5

/**
 * Worker secrets are set with `wrangler secret put` and are deliberately absent
 * from `wrangler.jsonc`, so they are not part of the generated binding types.
 */
type WorkerEnv = CloudflareEnv & {
  JOBS_SECRET?: string
}

type IncomingRequest = Request<unknown, IncomingRequestCfProperties>

const handler: ExportedHandler<WorkerEnv> = {
  fetch(request, env, ctx) {
    return openNextWorker.fetch(request, env, ctx)
  },

  async scheduled(event, env, ctx) {
    const secret = env.JOBS_SECRET
    if (!secret) {
      // Unconfigured means unavailable: refuse loudly rather than run an
      // unauthenticated job sweep.
      throw new Error('JOBS_SECRET is not configured; scheduled jobs did not run.')
    }
    if (!env.SITE_URL) {
      throw new Error('SITE_URL is not configured; scheduled jobs did not run.')
    }

    const url = new URL('/api/payload-jobs/run', env.SITE_URL)
    url.searchParams.set('limit', String(JOB_BATCH_LIMIT))

    // A synthetic request has no inbound `cf` properties; the adapter reads
    // `request.cf` defensively and leaves it undefined.
    const request = new Request(url, {
      method: 'GET',
      headers: { authorization: `Bearer ${secret}` },
    }) as IncomingRequest

    const response = await openNextWorker.fetch(request, env, ctx)

    if (!response.ok) {
      // Surface failure to the Cron Trigger so it is recorded as a failed run.
      throw new Error(
        `Scheduled job run failed with status ${response.status} at ${event.scheduledTime}.`,
      )
    }

    // Payload's /api/payload-jobs/run endpoint (payload/dist/queues/endpoints/run.js)
    // returns HTTP 200 even when individual jobs error — the body's
    // `remainingJobsFromQueried` counts jobs whose task result was
    // `status: 'error'` in this run. A 200 with failed jobs must not read as a
    // successful cron run.
    const body = (await response.json()) as { remainingJobsFromQueried?: number }
    if ((body.remainingJobsFromQueried ?? 0) > 0) {
      throw new Error(
        `Scheduled job run reported ${body.remainingJobsFromQueried} failed job(s) at ${event.scheduledTime}.`,
      )
    }
  },
}

export default handler
