// Writes `.env.local` and `supabase/functions/.env` from the running local
// Supabase stack (P03, D32). Local only: refuses unless `supabase status`
// reports a loopback API host. Never reads or touches `.env`, and never
// prints a key value.
import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'

const MARKER = '# Generated by `pnpm db:env` (scripts/local-env.mjs) — safe to delete and regenerate.'
const LOCAL_HOSTS = new Set(['127.0.0.1', 'localhost'])

const raw = execFileSync('supabase', ['status', '-o', 'json'], { encoding: 'utf8' })
const status = JSON.parse(raw)

const apiUrl = new URL(status.API_URL)
if (!LOCAL_HOSTS.has(apiUrl.hostname)) {
  console.error('Refusing: supabase status API_URL is not a local host.')
  process.exit(1)
}

const path = '.env.local'
if (existsSync(path) && !readFileSync(path, 'utf8').includes(MARKER)) {
  console.error(`Refusing to overwrite ${path}: it was not generated by this script.`)
  process.exit(1)
}

// Local-only email/webhook values (P06). The Turnstile secret is Cloudflare's
// documented always-pass test key (developers.cloudflare.com/turnstile/
// troubleshooting/testing) and the webhook secret is the Svix `whsec_` form of
// a fixed local string, so tests can sign real signatures. None of these may
// ever reach a production environment.
const localWebhookSecret = `whsec_${Buffer.from('anas-studio-local-webhook-secret-p06').toString('base64')}`

// D32: the server values belong to the Edge Functions, which read
// `supabase/functions/.env` (gitignored) on `supabase start`. They run in
// Docker, so they reach the host's Mailpit through host.docker.internal.
// RESEND_API_KEY is empty on purpose: with a local SITE_URL no real email is
// ever sent anyway (supabase/functions/_shared/email.ts).
//
// P08 (D38): payments run against the local Moyasar emulator
// (`pnpm emulator`, tests/support/moyasar-emulator.ts, port 54390 on the
// host), never against Moyasar. The key and the webhook secret are fixed local
// strings the emulator accepts; `sk_test_` only matches the documented prefix
// of a test key. FUNCTIONS_PUBLIC_URL is the functions' address as the
// emulator and the browser reach it (inside the runtime SUPABASE_URL is an
// internal address).
const functionValues = `SITE_URL=http://localhost:3000
JOBS_SECRET=local-jobs-secret-not-for-production
TOKEN_HASH_PEPPER=local-pepper-not-for-production
TURNSTILE_SECRET_KEY=1x0000000000000000000000000000000AA
RESEND_API_KEY=
EMAIL_DEV_MAILPIT_URL=http://host.docker.internal:54324
EMAIL_FROM="أنس <noreply@anas.studio>"
RESEND_WEBHOOK_SECRET=${localWebhookSecret}
MOYASAR_API_BASE_URL=http://host.docker.internal:54390/v1
MOYASAR_SECRET_KEY=sk_test_local_emulator_key_not_for_production
MOYASAR_WEBHOOK_SECRET=local-moyasar-webhook-secret-not-for-production
PAYMENTS_MODE=test
FUNCTIONS_PUBLIC_URL=${status.API_URL}/functions/v1
`

const functionsPath = 'supabase/functions/.env'
if (existsSync(functionsPath) && !readFileSync(functionsPath, 'utf8').includes(MARKER)) {
  console.error(`Refusing to overwrite ${functionsPath}: it was not generated by this script.`)
  process.exit(1)
}
writeFileSync(functionsPath, `${MARKER}\n${functionValues}`)
console.log(`Wrote ${functionsPath}.`)

// The Next app needs only the public Supabase values; the tests also read the
// function values here to sign webhook and jobs requests. The Turnstile site
// key is Cloudflare's documented always-pass test key, paired with the
// always-pass test secret above (P07 checkout widget, local only).
const content = `${MARKER}
NEXT_PUBLIC_SUPABASE_URL=${status.API_URL}
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${status.PUBLISHABLE_KEY}
NEXT_PUBLIC_TURNSTILE_SITE_KEY=1x00000000000000000000AA
# Same values as supabase/functions/.env, for the tests (local only)
${functionValues}`
writeFileSync(path, content)
console.log(`Wrote ${path}.`)
