// Writes `.env.local` from the running local Supabase stack (P03). Local
// only: refuses unless `supabase status` reports a loopback API host. Never
// reads or touches `.env`, and never prints a key value.
import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'

const MARKER = '# Generated by `pnpm db:env` (scripts/local-env.mjs) — safe to delete and regenerate.'
const LOCAL_HOSTS = new Set(['127.0.0.1', 'localhost'])

const raw = execFileSync('supabase', ['status', '-o', 'json'], { encoding: 'utf8' })
const status = JSON.parse(raw)

const apiUrl = new URL(status.API_URL)
if (!LOCAL_HOSTS.has(apiUrl.hostname)) {
  console.error('Refusing: supabase status API_URL is not a local host.')
  process.exit(1)
}

const path = '.env.local'
if (existsSync(path) && !readFileSync(path, 'utf8').includes(MARKER)) {
  console.error(`Refusing to overwrite ${path}: it was not generated by this script.`)
  process.exit(1)
}

const content = `${MARKER}
NEXT_PUBLIC_SUPABASE_URL=${status.API_URL}
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${status.PUBLISHABLE_KEY}
CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE=postgresql://app_server:app_server_local_only@127.0.0.1:54322/postgres
SITE_URL=http://localhost:3000
REVALIDATE_SECRET=local-revalidate-secret-not-for-production
`
writeFileSync(path, content)
console.log(`Wrote ${path}.`)
