/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgSchema,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  uuid,
  varchar,
  timestamp,
  numeric,
  jsonb,
  boolean,
  serial,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const db_schema = pgSchema("cms");
export const enum_users_role = db_schema.enum("enum_users_role", [
  "owner",
  "editor",
  "operations",
]);
export const enum_runtime_probe_status = db_schema.enum(
  "enum_runtime_probe_status",
  ["draft", "published"],
);
export const enum__runtime_probe_v_version_status = db_schema.enum(
  "enum__runtime_probe_v_version_status",
  ["draft", "published"],
);
export const enum_payload_jobs_log_task_slug = db_schema.enum(
  "enum_payload_jobs_log_task_slug",
  ["inline", "probeHeartbeat"],
);
export const enum_payload_jobs_log_state = db_schema.enum(
  "enum_payload_jobs_log_state",
  ["failed", "succeeded"],
);
export const enum_payload_jobs_task_slug = db_schema.enum(
  "enum_payload_jobs_task_slug",
  ["inline", "probeHeartbeat"],
);

export const users_sessions = db_schema.table(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = db_schema.table(
  "users",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    role: enum_users_role("role").notNull().default("owner"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    resetPasswordRequestedAt: timestamp("reset_password_requested_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const runtime_probe = db_schema.table(
  "runtime_probe",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    title: varchar("title"),
    body: jsonb("body"),
    attachment: uuid("attachment_id").references(() => runtime_probe_media.id, {
      onDelete: "set null",
    }),
    lastScheduledRunAt: timestamp("last_scheduled_run_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_runtime_probe_status("_status").default("draft"),
  },
  (columns) => [
    index("runtime_probe_attachment_idx").on(columns.attachment),
    index("runtime_probe_updated_at_idx").on(columns.updatedAt),
    index("runtime_probe_created_at_idx").on(columns.createdAt),
    index("runtime_probe__status_idx").on(columns._status),
  ],
);

export const _runtime_probe_v = db_schema.table(
  "_runtime_probe_v",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    parent: uuid("parent_id").references(() => runtime_probe.id, {
      onDelete: "set null",
    }),
    version_title: varchar("version_title"),
    version_body: jsonb("version_body"),
    version_attachment: uuid("version_attachment_id").references(
      () => runtime_probe_media.id,
      {
        onDelete: "set null",
      },
    ),
    version_lastScheduledRunAt: timestamp("version_last_scheduled_run_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__runtime_probe_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_runtime_probe_v_parent_idx").on(columns.parent),
    index("_runtime_probe_v_version_version_attachment_idx").on(
      columns.version_attachment,
    ),
    index("_runtime_probe_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_runtime_probe_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_runtime_probe_v_version_version__status_idx").on(
      columns.version__status,
    ),
    index("_runtime_probe_v_created_at_idx").on(columns.createdAt),
    index("_runtime_probe_v_updated_at_idx").on(columns.updatedAt),
    index("_runtime_probe_v_latest_idx").on(columns.latest),
  ],
);

export const runtime_probe_media = db_schema.table(
  "runtime_probe_media",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    alt: varchar("alt"),
    _objectKey: varchar("_objectkey"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
  },
  (columns) => [
    index("runtime_probe_media_updated_at_idx").on(columns.updatedAt),
    index("runtime_probe_media_created_at_idx").on(columns.createdAt),
    uniqueIndex("runtime_probe_media_filename_idx").on(columns.filename),
  ],
);

export const payload_kv = db_schema.table(
  "payload_kv",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_jobs_log = db_schema.table(
  "payload_jobs_log",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    executedAt: timestamp("executed_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    completedAt: timestamp("completed_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    taskSlug: enum_payload_jobs_log_task_slug("task_slug").notNull(),
    taskID: varchar("task_i_d").notNull(),
    input: jsonb("input"),
    output: jsonb("output"),
    state: enum_payload_jobs_log_state("state").notNull(),
    error: jsonb("error"),
  },
  (columns) => [
    index("payload_jobs_log_order_idx").on(columns._order),
    index("payload_jobs_log_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [payload_jobs.id],
      name: "payload_jobs_log_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_jobs = db_schema.table(
  "payload_jobs",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    input: jsonb("input"),
    completedAt: timestamp("completed_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    totalTried: numeric("total_tried", { mode: "number" }).default(0),
    hasError: boolean("has_error").default(false),
    error: jsonb("error"),
    taskSlug: enum_payload_jobs_task_slug("task_slug"),
    queue: varchar("queue").default("default"),
    waitUntil: timestamp("wait_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    processing: boolean("processing").default(false),
    meta: jsonb("meta"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_jobs_completed_at_idx").on(columns.completedAt),
    index("payload_jobs_total_tried_idx").on(columns.totalTried),
    index("payload_jobs_has_error_idx").on(columns.hasError),
    index("payload_jobs_task_slug_idx").on(columns.taskSlug),
    index("payload_jobs_queue_idx").on(columns.queue),
    index("payload_jobs_wait_until_idx").on(columns.waitUntil),
    index("payload_jobs_processing_idx").on(columns.processing),
    index("payload_jobs_updated_at_idx").on(columns.updatedAt),
    index("payload_jobs_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents = db_schema.table(
  "payload_locked_documents",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = db_schema.table(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: uuid("users_id"),
    "runtime-probeID": uuid("runtime_probe_id"),
    "runtime-probe-mediaID": uuid("runtime_probe_media_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_runtime_probe_id_idx").on(
      columns["runtime-probeID"],
    ),
    index("payload_locked_documents_rels_runtime_probe_media_id_idx").on(
      columns["runtime-probe-mediaID"],
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["runtime-probeID"]],
      foreignColumns: [runtime_probe.id],
      name: "payload_locked_documents_rels_runtime_probe_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["runtime-probe-mediaID"]],
      foreignColumns: [runtime_probe_media.id],
      name: "payload_locked_documents_rels_runtime_probe_media_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = db_schema.table(
  "payload_preferences",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = db_schema.table(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: uuid("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = db_schema.table(
  "payload_migrations",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_jobs_stats = db_schema.table("payload_jobs_stats", {
  id: uuid("id").defaultRandom().primaryKey(),
  stats: jsonb("stats"),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_runtime_probe = relations(runtime_probe, ({ one }) => ({
  attachment: one(runtime_probe_media, {
    fields: [runtime_probe.attachment],
    references: [runtime_probe_media.id],
    relationName: "attachment",
  }),
}));
export const relations__runtime_probe_v = relations(
  _runtime_probe_v,
  ({ one }) => ({
    parent: one(runtime_probe, {
      fields: [_runtime_probe_v.parent],
      references: [runtime_probe.id],
      relationName: "parent",
    }),
    version_attachment: one(runtime_probe_media, {
      fields: [_runtime_probe_v.version_attachment],
      references: [runtime_probe_media.id],
      relationName: "version_attachment",
    }),
  }),
);
export const relations_runtime_probe_media = relations(
  runtime_probe_media,
  () => ({}),
);
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_jobs_log = relations(
  payload_jobs_log,
  ({ one }) => ({
    _parentID: one(payload_jobs, {
      fields: [payload_jobs_log._parentID],
      references: [payload_jobs.id],
      relationName: "log",
    }),
  }),
);
export const relations_payload_jobs = relations(payload_jobs, ({ many }) => ({
  log: many(payload_jobs_log, {
    relationName: "log",
  }),
}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    "runtime-probeID": one(runtime_probe, {
      fields: [payload_locked_documents_rels["runtime-probeID"]],
      references: [runtime_probe.id],
      relationName: "runtime-probe",
    }),
    "runtime-probe-mediaID": one(runtime_probe_media, {
      fields: [payload_locked_documents_rels["runtime-probe-mediaID"]],
      references: [runtime_probe_media.id],
      relationName: "runtime-probe-media",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_payload_jobs_stats = relations(
  payload_jobs_stats,
  () => ({}),
);

type DatabaseSchema = {
  db_schema: typeof db_schema;
  enum_users_role: typeof enum_users_role;
  enum_runtime_probe_status: typeof enum_runtime_probe_status;
  enum__runtime_probe_v_version_status: typeof enum__runtime_probe_v_version_status;
  enum_payload_jobs_log_task_slug: typeof enum_payload_jobs_log_task_slug;
  enum_payload_jobs_log_state: typeof enum_payload_jobs_log_state;
  enum_payload_jobs_task_slug: typeof enum_payload_jobs_task_slug;
  users_sessions: typeof users_sessions;
  users: typeof users;
  runtime_probe: typeof runtime_probe;
  _runtime_probe_v: typeof _runtime_probe_v;
  runtime_probe_media: typeof runtime_probe_media;
  payload_kv: typeof payload_kv;
  payload_jobs_log: typeof payload_jobs_log;
  payload_jobs: typeof payload_jobs;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  payload_jobs_stats: typeof payload_jobs_stats;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_runtime_probe: typeof relations_runtime_probe;
  relations__runtime_probe_v: typeof relations__runtime_probe_v;
  relations_runtime_probe_media: typeof relations_runtime_probe_media;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_jobs_log: typeof relations_payload_jobs_log;
  relations_payload_jobs: typeof relations_payload_jobs;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_payload_jobs_stats: typeof relations_payload_jobs_stats;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
